config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :maps do
    resources :photos, only: [:create, :destroy]
  end
  get 'search', to: 'search#search'
  get '/tagged', to: "maps#tagged", as: :tagged
  resources :users, only: [:index, :show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  acts_as_taggable_on :tags
  belongs_to :user
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
# frozen_string_literal: true
require 'elasticsearch/model'

class User < ApplicationRecord
  attr_writer :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]
  has_many :maps
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
  
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  def as_indexed_json(options = {})
    self.as_json(
      only: [:id, :username]
    )
  end 

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h)
        .where(['lower(username) = :value OR lower(email) = :value',
                { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      conditions[:email].downcase! if conditions[:email]
      where(conditions.to_h).first
    end
  end

  settings analysis: {
    filter: {
      trigrams_filter: {
        type: 'ngram', min_gram: 3, max_gram: 3
      }
    },
    analyzer: {
      trigrams: {
        type: 'custom', tokenizer: 'standard', filter: ['lowercase', 'trigrams_filter']
      }
    }
  } do
    mapping do
      indexes :username
    end
  end
end
User.__elasticsearch__.create_index! force: true
User.import

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password,
                   :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/maps_controller.rb
# frozen_string_literal: true

class MapsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  def index
    @maps = Map.paginate(page: params[:page], per_page: 10)
  end

  def show; end

  def new
    @map = Map.new
  end

  def create
    @map = current_user.maps.create(map_params)
    if @map.valid?
      flash[:notice] = "Map successfully created"
      redirect_to map_path(@map)
    else
      flash[:alert] = "Something went wrong - Try again later"
      render :index, status: :unprocessable_entity
    end
  end

  def edit
    @map = Map.find(params[:id])
    if current_user != current_map.user
      return render plain: 'Not Allowed',
                    status: :forbidden
    end
  end

  def update
    if current_user != current_map.user
      return render plain: 'Not Allowed',
                    status: :forbidden
    end
    current_map.update_attributes(map_params)
    if current_map.valid?
      flash[:notice] = "Map successfully updated"
      redirect_to map_path(current_map)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    current_map.destroy
    redirect_to maps_path
  end

  def tagged
    if params[:tag].present?
      @maps = Map.tagged_with(params[:tag])
    else
      @maps = Map.all
    end
  end

  private

  helper_method :current_map

  def current_map
    @current_map ||= Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:name, :description, :picture, :tag_list)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @users = params[:q].nil? ? [] : User.search(
      query: {
        query_string: {
          default_operator: "AND",
          analyzer: "trigrams",
          query: "#{params[:q]}"
        }
      }
    ).results
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def index
    @recent_maps = Map.order(created_at: :desc).first(2)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/maps_helper.rb
# frozen_string_literal: true

module MapsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TavernTales</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark " style="background-color: #355940">
      <div class="container col-12 col-lg-6">
        <%= link_to "TavernTales", root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item <%= 'active' if params[:controller] == 'static_pages' %>">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item <%= 'active' if params[:controller] == 'maps' %>">
              <a class="nav-link" href="/maps">Maps</a>
            </li>
          </ul>
          <%= form_for search_path, method: :get, url: { controller: "/search", action: "search" }, html: { class:"form-inline my-2 my-lg-0"} do |f| %>
            <%= text_field_tag :q, params[:q], class:"form-control mr-sm-2", placeholder: "Find a user" %>
            <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0", name: nil %>
          <% end %>
          <ul class="navbar-nav">
            <% if current_user %>
              <li class="nav-item <%= 'active' if params[:controller] == 'users' %>">
                <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item <%= 'active' if params[:controller] == 'devise/sessions' %>">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% if notice.present? %>
      <div class="alert alert-success" style="text-align: center" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" style="text-align: center" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/maps/_form.html.erb
<div class="field">
  <%= f.label :name %>:
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :description %>:
  <br />
  <%= f.text_area :description, size: "60x12" %>
</div>

<div class="field">
  <%= f.label :tag_list, "Tags (separate by comma):" %>
  <% if action == "new" %>
    <%= f.text_field :tag_list %>
  <% elsif action == "edit" %>
    <%= f.text_field :tag_list, value: current_map.tag_list.to_s %>
  <% end %>
</div>

<div class="field">
  <%= f.label :picture %>:
  <%= f.file_field :picture %>    
</div>

<div class="actions">
  <%= f.submit "Save", class: "btn btn-secondary" %>
  <% if action == "new" %>
    <%= link_to "Cancel", maps_path, class: "btn btn-warning" %>
  <% elsif action == "edit" %>
    <%= link_to "Cancel", map_path(current_map), class: "btn btn-warning" %>
  <% end %>
</div>

app/views/maps/_map.html.erb
<div class="map-container">
  <div class="map-info">
    <h4 class="map-header"><%= link_to map.name, map_path(map) %></h4>
    <% map.tag_list.each do |tag| %>
      <span>
        <%= link_to tag, tagged_path(tag: tag), class:"badge badge-primary tag" %>
      </span>
    <% end %>
    <br />
    <div class="map-description">
      <p>
        <%= map.description %>
      </p>
    </div>
  </div>
  <div class="map-image">
    <%= image_tag map.picture.thumb.url, class:"map-thumb" %>
  </div>
</div>

app/views/maps/edit.html.erb
<div class="container col-12 col-lg-6">
  <h3>Edit Map</h3>
  <%= form_for @map, url: { action: "update" }, html: { multipart: true } do |form| %>
    <%= render partial: 'form', locals: { f: form, action: "edit" } %>
  <% end %>
  <%= link_to 'Delete Map', map_path(current_map), class: "btn btn-danger", method: :delete %>
</div>

app/views/maps/index.html.erb
<br />
<div class="container col-12 col-lg-6">
  <div class="row">
    <h3 class="col-6 col-lg-10">Maps</h3>
      <div class="col-6 col-lg-2">
        <%= link_to 'New map', new_map_path, class:'btn btn-secondary float-right' %>
      </div>
  </div>
  <div class="digg_pagination">
    <%= will_paginate @maps %>
  </div>
  <% @maps.each do |map| %>
    <%= render partial: 'map', locals: { map: map } %>
  <% end %>
  <div class="digg_pagination">
    <%= will_paginate @maps %>
  </div>
</div>

app/views/maps/new.html.erb
<div class="container col-12 col-lg-6">
  <h3>New Map</h3>
  <br />
  <%= form_for @map, html: { multipart: true } do |form| %>
    <%= render partial: 'form', locals: { f: form, action: "new" } %>
  <% end %>
</div>

app/views/maps/show.html.erb
<br />
<div class="container col-12 col-lg-6">
  <div class="row">
    <h3 class="col-10"><%= current_map.name %></h3>
    <% if current_map.user == current_user %>
      <%= link_to 'Edit map', edit_map_path(current_map), class:'btn btn-secondary' %>
    <% end %>
  </div>
  Created by: <%= current_map.user.username%>
  <br />
  <p style="text-align:center">
    <%= link_to image_tag(current_map.picture.preview.url), current_map.picture.url, id: "picture" %>
  </p>
  <h3>Description</h3>
  <p><%= current_map.description %></p>
  <h3>Tags</h3>
  <% current_map.tag_list.each do |tag| %>
    <span class="badge badge-primary tag"><%= tag %></span>
  <% end %>
</div>

app/views/maps/tagged.html.erb
<br />
<div class="container col-12 col-lg-6">
  <h3>Maps with '<%= params[:tag] %>'</h3>
  <div class="digg_pagination">
    <%= will_paginate @maps %>
  </div>
  <% @maps.each do |map| %>
    <%= render partial: 'map', locals: { map: map } %>
  <% end %>
  <div class="digg_pagination">
    <%= will_paginate @maps %>
  </div>
</div>

app/views/search/search.html.erb
<div class="container col-6">
  <h1>User Search</h1>
  <h3><%= @users.count %> results found</h3>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.username, controller: "users", action: "show", id: user._id%>
      </li>
    <% end %>
  </ul>
</div>

app/views/static_pages/index.html.erb
<div class="container col-12 col-lg-6">
  <h1>Welcome to Tavern Tales!</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <% unless @recent_maps.empty? %>
    <h2>Recent Maps</h2>
    <div class="row justify-content-between">
      <% @recent_maps.each do |map| %>
        <div class="col-6 justify-content-center">
          <div class="col-12 shadow p-3 mb-5 bg-white rounded">
            <div class="row">
              <div class="col-8">
                <h3><%= link_to map.name, map_path(map) %></h3>
                by: <%= link_to map.user.username, user_path(map.user) %>
                <br />
                <% map.tag_list.first(3).each do |tag| %>
                  <%= link_to tag, tagged_path(tag: tag), class:"badge badge-primary tag" %>
                <% end %>
              </div>
              <div class="col-4">
                <%= image_tag map.picture.thumb.url %>
              </div>
            </div>
            <div class="row">
              <div class="container">
                <%= map.description %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container col-12 col-lg-6">
  <h1>Users</h1>
  <div class="digg_pagination">
    <%= will_paginate @users %>
  </div>
  <% @users.each do |user| %>
    <div class="user-box">
      <h3><%= link_to user.username, user_path(user) %></h3>
    </div>
  <% end %>
  <div class="digg_pagination">
    <%= will_paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container col-12 col-lg-6">
  <h3><%= @user.username %><h3>
  <% if current_user == @user %>
    <p><%= link_to 'Edit Profile', edit_user_registration_path %></p>
  <% end %>
  <h4>Uploaded Maps</h4>
  <div class="maps-index">
    <% if @user.maps %>
      <ul>
        <% @user.maps.each do |map| %>
          <li><%= link_to map.name, map_path(map) %></li>
        <% end %>
      </ul>
    <% else %>
      <p>No maps yet.</p>
    <% end %>
  </div>
</div>